# Site settings
title: CENG 2002
email: pembeci@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Code, exercices, and lecture notes site to be used in MSKU CENG 2002 Course.
baseurl: "/ceng2002" # the subpath of your site, e.g. /blog/
github_username:  pembeci

# Build settings
markdown: kramdown

# code
syntax-highlighting:
  enabled : true
  css: syntax.css
